/**
 * Image slots, and the paths derived from them.
 *
 * A "slot" is a position on the site that holds a photograph — `cities/lisboa`,
 * `portfolio/wedding/2` — and it is the key everything else is derived from:
 * the rendered AVIF and WebP files, the share card, and the credit entry. The
 * slots themselves are declared in `scripts/photos/targets.ts` and derived from
 * the catalogue, so a place or a service cannot exist without one.
 *
 * Paths are not stored on the catalogue data. They are computed here, and the
 * files are listed in `src/lib/data/image-manifest.ts`, which is generated by
 * `npm run photos:fetch`.
 */
import { IMAGE_SLOTS } from './data/image-manifest';
import { SITE_URL } from './site';

/** Root-relative path to the branded fallback OG image (1200×630). */
export const DEFAULT_OG_IMAGE = '/og-default.png';
export const DEFAULT_OG_IMAGE_WIDTH = 1200;
export const DEFAULT_OG_IMAGE_HEIGHT = 630;

/** The slot holding a place's hero photograph. */
export function citySlot(slug: string): string {
  return `cities/${slug}`;
}

/** The slot holding a service's card photograph. */
export function serviceSlot(slug: string): string {
  return `services/${slug}`;
}

/** One frame of a place's gallery, 1-indexed. */
export function gallerySlot(citySlug: string, index: number): string {
  return `gallery/${citySlug}/${index}`;
}

/**
 * The 1200×630 JPEG share card for a slot, or the branded default.
 *
 * JPEG rather than the AVIF the page itself serves, because social scrapers do
 * not negotiate a `<picture>` and several of them decode nothing newer.
 */
export function ogImagePath(slot: string): string {
  return IMAGE_SLOTS[slot]?.og ?? DEFAULT_OG_IMAGE;
}

/** Whether a slot has a photograph at all. */
export function hasImage(slot: string): boolean {
  return slot in IMAGE_SLOTS;
}

/** Turn a root-relative (or already-absolute) image path into an absolute URL. */
export function absoluteOgImage(path: string): string {
  if (/^https?:\/\//.test(path)) return path;
  return `${SITE_URL}${path.startsWith('/') ? '' : '/'}${path}`;
}
