/**
 * Records what is in `public/images/` as a TypeScript module.
 *
 * Two modules used to answer this question by asking the filesystem —
 * `portfolio.ts` with `readdirSync`, `seo.ts` with `existsSync`. That works
 * while a page is prerendered during the build and fails silently the moment
 * the same page is rendered on demand, because a Cloudflare Worker has no
 * filesystem: galleries came back empty and `og:image` fell back to the brand
 * default, on exactly the pages Next chose not to prerender.
 *
 * Running at build time turns the same question into data that ships with the
 * bundle, so it answers identically wherever the page renders.
 *
 * The output is committed so a fresh clone typechecks; the build regenerates it,
 * and a diff means the images on disk changed without this being rerun.
 */
import { readdirSync, statSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';

const ROOT = process.cwd();
const IMAGES_ROOT = join(ROOT, 'public', 'images');
const PORTFOLIO_ROOT = join(IMAGES_ROOT, 'portfolio');
const OUT = join(ROOT, 'src', 'lib', 'data', 'public-images.ts');

const IMAGE_PATTERN = /\.(jpe?g|png|webp|avif|svg)$/i;
/** Matches `portfolioImages`: the gallery shows at most five per service. */
const MAX_PORTFOLIO_IMAGES = 5;

/** Every image file under `dir`, recursively, as paths relative to `public/`. */
function walk(dir: string): string[] {
  const found: string[] = [];
  for (const entry of readdirSync(dir)) {
    const abs = join(dir, entry);
    if (statSync(abs).isDirectory()) {
      found.push(...walk(abs));
      continue;
    }
    if (IMAGE_PATTERN.test(entry)) {
      found.push(`/${relative(join(ROOT, 'public'), abs)}`);
    }
  }
  return found;
}

/** Directory entries sorted the way a human numbers files: 2.jpg before 10.jpg. */
function byNumber(a: string, b: string): number {
  return a.localeCompare(b, undefined, { numeric: true });
}

function portfolioBySlug(): Record<string, string[]> {
  const bySlug: Record<string, string[]> = {};
  for (const slug of readdirSync(PORTFOLIO_ROOT).sort()) {
    const dir = join(PORTFOLIO_ROOT, slug);
    if (!statSync(dir).isDirectory()) continue;
    const images = readdirSync(dir)
      .filter((file) => IMAGE_PATTERN.test(file))
      .sort(byNumber)
      .slice(0, MAX_PORTFOLIO_IMAGES)
      .map((file) => `/images/portfolio/${slug}/${file}`);
    if (images.length > 0) bySlug[slug] = images;
  }
  return bySlug;
}

function main(): void {
  const all = walk(IMAGES_ROOT).sort();
  const portfolio = portfolioBySlug();

  const file = `// GENERATED by scripts/generate-public-images.ts — do not edit by hand.
// Run \`npm run build\` (or the script directly) after adding or removing images.

/** Every image under \`public/images/\`, as the path the browser requests. */
export const PUBLIC_IMAGES: readonly string[] = ${JSON.stringify(all, null, 2)};

/** Portfolio galleries by service slug, sorted, capped at ${MAX_PORTFOLIO_IMAGES} per service. */
export const PORTFOLIO_IMAGES: Readonly<Record<string, readonly string[]>> = ${JSON.stringify(
    portfolio,
    null,
    2,
  )};
`;

  writeFileSync(OUT, file);
  const galleries = Object.keys(portfolio).length;
  console.log(
    `[public-images] ${all.length} images, ${galleries} galleries → ${relative(ROOT, OUT)}`,
  );
}

main();
