// GENERATED by scripts/photos/fetch.ts — do not edit by hand.
// Run `npm run photos:fetch` after selecting photographs.

/** One rendered file. */
export interface ImageSource {
  path: string;
  width: number;
}

/** Everything needed to render a slot without asking the filesystem. */
export interface ImageSlot {
  /** Intrinsic size of the largest rendered derivative, for width/height. */
  width: number;
  height: number;
  /** Dominant colour, painted behind the image so nothing flashes white. */
  color: string | null;
  avif: ImageSource[];
  webp: ImageSource[];
  /** 1200x630 JPEG share card, where the slot has one. */
  og?: string;
}

/**
 * Every image the site can render, keyed by slot.
 *
 * Generated rather than discovered. `readdirSync` works during a prerender and
 * silently answers "nothing" on a Worker, which is how galleries came back
 * empty on exactly the pages Next chose not to prerender.
 */
export const IMAGE_SLOTS: Readonly<Record<string, ImageSlot>> = {};
