// GENERATED by scripts/generate-public-images.ts — do not edit by hand.
// Run `npm run build` (or the script directly) after adding or removing images.

/** Every image under `public/images/`, as the path the browser requests. */
export const PUBLIC_IMAGES: readonly string[] = [];

/** Portfolio galleries by service slug, sorted, capped at 5 per service. */
export const PORTFOLIO_IMAGES: Readonly<Record<string, readonly string[]>> = {};
